config/routes.rb
JKLeadEngine::Application.routes.draw do
  devise_for :users
  get "admin/index"
  resources :organizations
  resources :organizations do
    post 'organization_upload', :on => :collection
  end
  get "home/index"
  get "home/admin"
  get "home/get_current_user"
  resources :events
  match "admin" => "admin#index" ,via: [:get]

   root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name, analyzer: 'text', index_options: 'offsets'
      indexes :email, analyzer: 'text'
    end
  end
  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                #query_string: {
                #   fields:  ['name^10', 'email','phone','website'],
                #   query: query
                #  }
                multi_match: {
                    query: "*#{query}*",
                    fields: ['name^10', 'email','phone','website']
                }
            }
        }
    )
  end
end
Organization.import

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  respond_to :html, :json
  protect_from_forgery with: :exception

  layout :decide_layout

  private
  def decide_layout
    "#{controller_name}" == "admin" ? "admin_application" : "application"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_date, :values_type, :message, :status, :result, :user_id, :company_id, :campaign_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def admin
    render "layouts/admin_application"
  end
  def get_current_user
    user = {}
    respond_to do |format|
      if user_signed_in?
        user = current_user
        format.json { render json: user ,:status => 200}
      else
        format.json { render json: user ,:status => 404}
      end
    end
  end
end

app/controllers/organizations_controller.rb
require 'csv'
class OrganizationsController < ApplicationController
  #before_filter :authenticate_user!
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
    respond_to do |format|
      format.json { render json: OrganizationsDatatable.new(view_context) }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
  def organization_upload
    flash[:notice] = "File uploaded Succesfully."
    organizations = []
    @update_count=0
    @create_count=0
    @count = 0
    if !params[:file].blank?
      CSV.foreach(params[:file].tempfile,:encoding => 'windows-1251:utf-8') { |row|
        row = row.first.split(",") if row.count == 1
        organization_date = {}
        organization_date["name"] = row[0]
        organization_date["email"] = row[1]
        organization_date["website"] = row[2]
        organization_date["twitter"] = row[3]
        organization_date["facebook"] = row[4]
        organization_date["phone"] = row[5]
        organization_date["remarks"] = row[6]
        organization_date["event_id"] = row[7]
        organizations << organization_date
      }
      #remove first row with column name and make a new array with activitys
      organizations = organizations[1..organizations.length]
    end
    #puts organizations.to_json
    @total_count = organizations.count
    if params[:count].blank?
      @count = 0
    else
      @count = params[:count].to_i + 1
    end

    if !organizations[@count].blank?
        @organization = Organization.new
        @organization.name=organizations[@count]["name"]
        @organization.email=organizations[@count]["email"]
        @organization.website=organizations[@count]["website"]
        @organization.twitter=organizations[@count]["twitter"]
        @organization.facebook=organizations[@count]["facebook"]
        @organization.phone=organizations[@count]["phone"]
        @organization.remarks=organizations[@count]["remarks"]
        @organization.event_id=organizations[@count]["event_id"]
        @organization.save
      end
    #respond_to do |format|
    #  format.json {render json: {data:{update_count:@update_count,create_count:@create_count,count:@count,total_count:@total_count}}}
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :email, :website, :twitter, :facebook, :phone, :remarks, :event_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :values_type %><br>
    <%= f.text_field :values_type %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :campaign_id %><br>
    <%= f.text_field :campaign_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event date</th>
      <th>Values type</th>
      <th>Message</th>
      <th>Status</th>
      <th>Result</th>
      <th>User</th>
      <th>Company</th>
      <th>Campaign</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_date %></td>
        <td><%= event.values_type %></td>
        <td><%= event.message %></td>
        <td><%= event.status %></td>
        <td><%= event.result %></td>
        <td><%= event.user_id %></td>
        <td><%= event.company_id %></td>
        <td><%= event.campaign_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Values type:</strong>
  <%= @event.values_type %>
</p>

<p>
  <strong>Message:</strong>
  <%= @event.message %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Result:</strong>
  <%= @event.result %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @event.company_id %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @event.campaign_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_admin_header.html.erb
<header class="header">
<a href="/admin/#/admin" class="logo">
  <!-- Add the class icon to your logo image or logo icon to add the margining -->
  JKLeadEngine
</a>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top" role="navigation" id="navbar-static-top">
<!-- Sidebar toggle button-->
<a href="javascript:void(0);" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button" id="sidebar-toggle">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<div class="navbar-right">
<ul class="nav navbar-nav">
<!-- Messages: style can be found in dropdown.less-->
<li class="dropdown messages-menu">
  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-envelope"></i>
    <span class="label label-success">4</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 4 messages</li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li><!-- start message -->
          <a href="javascript:void(0);">
            <div class="pull-left">
              <img src="img/avatar3.png" class="img-circle" alt="User Image"/>
            </div>
            <h4>
              Support Team
              <small><i class="fa fa-clock-o"></i> 5 mins</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li><!-- end message -->
        <li>
          <a href="javascript:void(0);">
            <div class="pull-left">
              <img src="img/avatar2.png" class="img-circle" alt="user image"/>
            </div>
            <h4>
              AdminLTE Design Team
              <small><i class="fa fa-clock-o"></i> 2 hours</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <div class="pull-left">
              <img src="img/avatar.png" class="img-circle" alt="user image"/>
            </div>
            <h4>
              Developers
              <small><i class="fa fa-clock-o"></i> Today</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <div class="pull-left">
              <img src="img/avatar2.png" class="img-circle" alt="user image"/>
            </div>
            <h4>
              Sales Department
              <small><i class="fa fa-clock-o"></i> Yesterday</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <div class="pull-left">
              <img src="img/avatar.png" class="img-circle" alt="user image"/>
            </div>
            <h4>
              Reviewers
              <small><i class="fa fa-clock-o"></i> 2 days</small>
            </h4>
            <p>Why not buy a new awesome theme?</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="footer"><a href="javascript:void(0);">See All Messages</a></li>
  </ul>
</li>
<!-- Notifications: style can be found in dropdown.less -->
<li class="dropdown notifications-menu">
  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-warning"></i>
    <span class="label label-warning">10</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 10 notifications</li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li>
          <a href="javascript:void(0);">
            <i class="ion ion-ios7-people info"></i> 5 new members joined today
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <i class="fa fa-warning danger"></i> Very long description here that may not fit into the page and may cause design problems
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <i class="fa fa-users warning"></i> 5 new members joined
          </a>
        </li>

        <li>
          <a href="javascript:void(0);">
            <i class="ion ion-ios7-cart success"></i> 25 sales made
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <i class="ion ion-ios7-person danger"></i> You changed your username
          </a>
        </li>
      </ul>
    </li>
    <li class="footer"><a href="javascript:void(0);">View all</a></li>
  </ul>
</li>
<!-- Tasks: style can be found in dropdown.less -->
<li class="dropdown tasks-menu">
  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-tasks"></i>
    <span class="label label-danger">9</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header">You have 9 tasks</li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li><!-- Task item -->
          <a href="javascript:void(0);">
            <h3>
              Design some buttons
              <small class="pull-right">20%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">20% Complete</span>
              </div>
            </div>
          </a>
        </li><!-- end task item -->
        <li><!-- Task item -->
          <a href="javascript:void(0);">
            <h3>
              Create a nice theme
              <small class="pull-right">40%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">40% Complete</span>
              </div>
            </div>
          </a>
        </li><!-- end task item -->
        <li><!-- Task item -->
          <a href="javascript:void(0);">
            <h3>
              Some task I need to do
              <small class="pull-right">60%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">60% Complete</span>
              </div>
            </div>
          </a>
        </li><!-- end task item -->
        <li><!-- Task item -->
          <a href="javascript:void(0);">
            <h3>
              Make beautiful transitions
              <small class="pull-right">80%</small>
            </h3>
            <div class="progress xs">
              <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                <span class="sr-only">80% Complete</span>
              </div>
            </div>
          </a>
        </li><!-- end task item -->
      </ul>
    </li>
    <li class="footer">
      <a href="javascript:void(0);">View all tasks</a>
    </li>
  </ul>
</li>
<!-- User Account: style can be found in dropdown.less -->
<li class="dropdown user user-menu">
  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
    <i class="glyphicon glyphicon-user"></i>
    <span>Jane Doe <i class="caret"></i></span>
  </a>
  <ul class="dropdown-menu">
    <!-- User image -->
    <li class="user-header bg-light-blue">
      <img src="img/avatar3.png" class="img-circle" alt="User Image" />
      <p>
        Jane Doe - Web Developer
        <small>Member since Nov. 2012</small>
      </p>
    </li>
    <!-- Menu Body -->
    <li class="user-body">
      <div class="col-xs-4 text-center">
        <a href="javascript:void(0);">Followers</a>
      </div>
      <div class="col-xs-4 text-center">
        <a href="javascript:void(0);">Sales</a>
      </div>
      <div class="col-xs-4 text-center">
        <a href="javascript:void(0);">Friends</a>
      </div>
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a href="javascript:void(0);" class="btn btn-default btn-flat">Profile</a>
      </div>
      <div class="pull-right">
        <a href="javascript:void(0);" class="btn btn-default btn-flat">Sign out</a>
      </div>
    </li>
  </ul>
</li>
</ul>
</div>
</nav>
</header>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-md-8 footer_render" style="padding-top:20px;padding-left:0px !important;">
          <div style="float:left;padding-right:20px;">
            <a href="javascript:void(0);" class="whiteboldlink">About Us</a>
          </div>
          <div style="float:left;padding-right:20px;">
            <a href="javascript:void(0);" class="whiteboldlink"> FAQ </a>
          </div>
          <div style="float:left;padding-right:20px;">
            <a href="javascript:void(0);" class="whiteboldlink">Contact Us </a>
          </div>
          <div style="float:left;padding-right:20px;">
            <a href="/#/login" class="whiteboldlink">Log In</a>
          </div>

        </div>
        <div class="col-md-1"></div>
        <div class="pull-right shareicon" style="padding-right:70px !important;">
          <div class="social_test">
            <a href="javascript:void(0);" target="_blank">
              <div class="social_test rss socila_hover"></div>
            </a>
          </div>
          <div class="social_test">
            <a href="javascript:void(0);" target="_blank">
              <div class="social_test twitter socila_hover"></div>
            </a>
          </div>
          <div class="social_test">
            <a href="javascript:void(0);" target="_blank">
              <div class=" social_test linkedin socila_hover"></div>
            </a>
          </div>
        </div>
      </div>

      <div class="row" style="padding-top:10px !important;">
        <div class="col-md-4" style="padding:0px !important;font-size:11px;">
          Copyright @ 2014 jakers . All rights reserved.
        </div>
        <div class="col-md-4"></div>
        <div class="pull-right" style="font-size:11px !important;padding-top:2px !important;padding-right:52px !important;">
          <div style="padding:0px !important;float:left;padding:2px !important;">
            <a href="javascript:void(0);" class="whiteboldlink">Privacy Notice</a>
          </div>
          <div style="padding:0px !important;float:left;padding:2px !important;">
            <p style="color:white;">/</p>
          </div>
          <div style="padding:0px !important;float:left;padding:2px !important;">
            <a href="javascript:void(0);" class="whiteboldlink">Terms of Use</a>
          </div>
        </div>
      </div>
      <div style="clear:both;height:10px !important;"></div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">JKLead Engine</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#">About</a>
        </li>
        <li class="active">
          <a href="#">Services</a>
        </li>
        <li>
          <a href="#">Contact</a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">States<b class="caret"></b></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <a href="/#/organizations">Organization</a>
            </li>
            <li>
              <a href="#">Auto Auctions</a>
            </li>
            <li>
              <a href="#">Real Estate Auctions</a>
            </li>
            <li>
              <a href="#">Foreclosure Auctions</a>
            </li>
            <li>
              <a href="#">Estate Sales</a>
            </li>
            <li>
              <a href="#">Online Auctions</a>
            </li>
            <li>
              <a href="#"> Art and Antique Auctions</a>
            </li>
            <li>
              <a href="#">Government Auctions</a>
            </li>
            <li>
              <a href="#">Police Auctions</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>JKLeadEngine</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application", controller_name %>
  <link href="<%= asset_path('JKAdmin.css') %>" rel="stylesheet" type="text/css" />
  <%= csrf_meta_tags %>
  <script src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" type="text/javascript"></script>
  <script src="//cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
  <link href="//cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css" media="all" rel="stylesheet" />


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<html ng-app="organization">
<body>

<%= render "layouts/header"%>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div ng-view>
<%= yield %>
</div>
<%= render "layouts/footer"%>
</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/organization_upload.js.erb
<% if @count < @total_count %>
<% bar_value = 100.to_f / @total_count.to_f %>
<% person_width = (@count+1)*bar_value %>
fd = new FormData();
fd.append('count',<%=@count%>)
fd.append('file', $scope.organizationfile);
$http.post("/organizations/organization_upload.js", fd, {
    transformRequest: angular.identity,
    headers: {'Content-Type': undefined}
}).success(function(data, status, headers, config){
    eval(data)
});
$("#progress-bar").css("width","<%=person_width%>%");
<% else %>
$("#progress-bar").css("width","100%");
$('#fileuploadsucess').html("<div class='alert alert-success' role='alert'>File Upload Successful</div>");
/*global window: false */
window.location.reload(true);
//$('#fileuploadModel').modal('hide');
<% end %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @organization.website %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @organization.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @organization.facebook %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @organization.remarks %>
</p>

<p>
  <strong>Event:</strong>
  <%= @organization.event_id %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>